### ISSUE TITLE
0.8.3-all not self-contained

### ISSUE THREAD

**Issue by andreak** [impossibl/pgjdbc-ng#446]
Hi.

I thought the point of the 0.8.3-all artifact was to avoid dependencies on netty, but I see that netty _is_ dragged in transitively.
Without the netty-jars on the class-path any Exception from the DB results in `java.lang.NoClassDefFoundError: io/netty/util/internal/OutOfDirectMemoryError` 

So, is there something wrong with the shading or am I misunderstanding something?

**Comment by kdubb** [comment]
#### Publishing
Apparently it has been publishing incorrectly for a long time (maybe forever). Adding a classifier like `all` means the jar is still published under the same pom; meaning regardless of it containing all the classes it still lists them as dependencies. This shouldn't affect anybody downloading the jar file and using it on the class path.

I've switched to it publishing `pgjdbc-ng-all` as the uber jar and it should be usable without any transitive dependencies. I've published test versions in the latest `0.9-SNAPSHOT`.

#### Exception
I've verified the JAR is relocating the dependencies as expected and contains the `OutOfDirectMemoryError` being reported; this is also happening in the 0.8.3 release. I can only imaging that something is getting confused and the regular jar is being referenced instead of the `all` variant.  I'm gonna. setup a little test to verify.

**Comment by kdubb** [comment]
I _believe_ I've verified the uber jar variant works using the published `0.9-SNAPSHOT` and the small test shown below.  It'd be great if you could verify it with whatever scenario you experienced the original error.


The test class (the `INVALID SQL` query is to ensure exceptions are reported)...
```java
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

public class JDBCTest {

	public static void main(String[] args) throws Exception {
		try (Connection conn = DriverManager.getConnection("jdbc:pgsql://test:test@localhost/test")) {
			try (Statement stmt = conn.createStatement()) {
				try(ResultSet rs = stmt.executeQuery("SELECT 1")) {
					rs.next();
					System.out.println("getInt = " + rs.getInt(1));
				}
				stmt.executeQuery("INVALID SQL");
			}
		}
	}

}
```

executed using...
```bash
java -cp pgjdbc-ng-all-0.9-SNAPSHOT.jar:JDBCTest.class JDBCTest
```
